# release.yml

changelog:
  exclude:
    type:
      - ignore-for-release

  categories:
    - title: Improvements
      type:
        - enhancement

    - title: Bug Fixes
      type:
        - bug

    - title: Documentaion
      type:
        - documentaion

    - title: Other Changes
      type:
        - "*"
