# release.yml

changelog:
  exclude:
    labels:
      - "Exclude from release nodes"

  categories:
    - title: Improvements
      type:
        - enhancement

    - title: Bug Fixes
      type:
        - bug

    - title: Documentaion
      type:
        - documentaion

    - title: Other Changes
      type:
        - "*"
